config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  get 'events/show'
  devise_for :users
  root to: "spots#index"
  resources :spots
  resources :events
  resources :areas
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base

  self.data = [
    { id: 0, name: 'エリアを選択してください' },
    { id: 1, name: '高松市' },
    { id: 2, name: '東讃エリア' },
    { id: 3, name: '中讃エリア' },
    { id: 4, name: '西讃エリア' },
    { id: 5, name: '島エリア' }
  ]

  include ActiveHash::Associations
  has_many :spots
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :spot
  # has_one_attached :image

end

app/models/spot.rb
class Spot < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  has_many :events, dependent: :destroy

  # presence: true do
  has_one_attached :image

  
  with_options presence: true do
    validates :image
    validates :user_id
    validates :spot_name
    validates :area_id, numericality: { other_than: 0 , message: "can't be blank"}
    validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/, message: 'を入力してください' }
    validates :address
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: "is invalid"}
  end


end





private

def image_content_type
  extension = ['image/png', 'image/jpg', 'image/jpeg']
  errors.add(:image, "の拡張子が間違っています") unless image.content_type.in?(extension)
end

def was_attached?
  self.image.attached?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :spots, dependent: :destroy

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?


  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update]


  def index
    @events = Event.all.order('end_time asc')
  end

  def new
    @event = Event.new
  end




  def show
    @event = Event.find(params[:id])
  end
end

def create
  @event = Event.new(event_params)
  if @event.save
    redirect_to root_path
  else
    render :new
  end
end

def update
  @event = Event.new(event_params)
  if @event.save
    redirect_to root_path
  else
    event :new
  end
end

def destroy
  @event.destroy

  flash[:success] = "Your Post has been removed."
  redirect_to root_path
end 


private
def event_params
  params.require(:event).permit(
    :event_name, 
    :image
  ).merge(user_id: current_user.id)
end

def set_event
  @event = Event.find(params[:id])
  

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_spot, only: [:show, :edit, :update]

  def index
    @spots = Spot.order(updated_at: :desc)
  end

  def new
    @spot = Spot.new
  end

  def show    
  end


  def edit
    # if current_user.id !=  @spot.user_id || @current_user.present?
    #  redirect_to root_path
    # end
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def update
    if @spot.update(spot_params)
       redirect_to spot_path(@spot.id)
    else
       render :edit
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    redirect_to root_path(@spot.id) unless current_user.id == @spot.user_id
    @spot.destroy
    redirect_to root_path
  end 
  
  
  def edit
    if current_user.id != @spot.user_id
      redirect_to root_path
    end
  end
  

  
private

  def spot_params
    params.require(:spot).permit(
      :spot_name, 
      :area_id, 
      :postal_code, 
      :address, 
      :building, 
      :phone_number, 
      :image
    ).merge(user_id: current_user.id)
  end

  def set_spot
    @spot = Spot.find(params[:id])
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets
  end
  
end

app/views/events/index.html.erb
<h1>Haco ここ</h1><br><br>
<h2>出品された箱についての情報</h2><br>

<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
<footer class="footer">
  <ul class="horizontal-list">
      <li class="horizontal-item"><a href="#">ABOUT US</a></li>
      <li class="horizontal-item"><a href="#">SITE MAP</a></li>
      <li class="horizontal-item"><a href="#">SNS</a></li>
      <li class="horizontal-item"><a href="#">CONTACT</a></li>
  </ul>
</footer>
</div>

  <% @events.each do |event| %>
  <div class="box col3" style="background-image">
    <a href="#">
    <%= image_tag("image_yasai_1", alt: "event.event_id")%>
    <div class="category"><%= event.event_title %></div>
    <p class="description">設置終了:<%= event.end_time %></p>
    </a>
  </div>
  <% end %>


<div class="box col5">
   <a href="#">
  <%= image_tag("image_L_1.jpg", alt: "HOT TOPICS")%>
  <div class="category">HOT TOPICS</div>
  <p class="description">Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit, sed do eiusmod tempor incididunt 
  ut labore et dolore magna aliqua. </p>
  </a>
</div>

<div class="box col5">
   <a href="#">
  <%= image_tag("image_M_4.jpg", alt: "HOT TOPICS")%>
  <div class="category">HOT TOPICS</div>
  <p class="description">Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit, sed do eiusmod tempor incididunt 
  ut labore et dolore magna aliqua. </p>
 </a>
</div>

   <div class="box col2">
    <a href="#">
    <%= image_tag("image_S_1.jpg", alt: "HOT TOPICS")%>
    <div class="category">HOT TOPICS</div>
    <p class="description">Lorem ipsum dolor sit amet, 
    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna aliqua. </p>
    </a>
    </div>
 
<div class="box col2">
   <a href="#">
  <%= image_tag("image_S_2.jpg", alt: "HOT TOPICS")%>
  <div class="category">HOT TOPICS</div>
  <p class="description">Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit, sed do eiusmod tempor incididunt 
  ut labore et dolore magna aliqua. </p>
 </a>
</div>

 <div class="box col1">
    <a href="#">
      <%= image_tag("image_S_7.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet... </p>
    </a>
  </div>

 <div class="box col1">
    <a href="#">
      <%= image_tag("image_S_8.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet... </p>
    </a>
  </div>

 <div class="box col1">
    <a href="#">
      <%= image_tag("image_S_5.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet... </p>
    </a>
  </div>

<div class="box col1">
   <a href="#">
  <%= image_tag("image_S_6.jpg", alt: "HOT TOPICS")%>
  <div class="category">HOT TOPICS</div>
  <p class="description">Lorem ipsum dolor sit amet... </p>
 </a>
</div>

  <div class="box col1">
    <a href="#">
    <%= image_tag("image_S_9.jpg", alt: "HOT TOPICS")%>
    <div class="category">HOT TOPICS</div>
    <p class="description">Lorem ipsum dolor sit amet... </p>
    </a>
  </div>

  <div class="box col1">
    <a href="#">
      <%= image_tag("image_S_8.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet... </p>
    </a>
  </div>


  <div class="box col2">
    <a href="#">
    <%= image_tag("image_S_10.jpg", alt: "HOT TOPICS")%>
    <div class="category">HOT TOPICS</div>
    <p class="description">Lorem ipsum dolor sit amet, 
    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna aliqua. </p>
   </a>
  </div>

  <div class="box col2">
    <a href="#">
    <%= image_tag("image_S_2.jpg", alt: "HOT TOPICS")%>
    <div class="category">HOT TOPICS</div>
    <p class="description">Lorem ipsum dolor sit amet, 
    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna aliqua. </p>
    </a>
    </div>

    <div class="box col5">
    <a href="#">
    <%= image_tag("image_M_1.jpg", alt: "HOT TOPICS")%>
    <div class="category">HOT TOPICS</div>
    <p class="description">Lorem ipsum dolor sit amet, 
    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna aliqua. </p>
   </a>
  </div>

  <div class="box col5">
      <a href="#">
      <%= image_tag("image_M_2.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet, 
      consectetur adipiscing elit, sed do eiusmod tempor incididunt 
      ut labore et dolore magna aliqua. </p>
    </a>
  </div>
  
    <div class="box col2">
      <a href="#">
      <%= image_tag("image_S_2.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet, 
      consectetur adipiscing elit, sed do eiusmod tempor incididunt 
      ut labore et dolore magna aliqua. </p>
    </a>
    </div>

    <div class="box col2">
        <a href="#">
        <%= image_tag("image_S_2.jpg", alt: "HOT TOPICS")%>
        <div class="category">HOT TOPICS</div>
        <p class="description">Lorem ipsum dolor sit amet, 
        consectetur adipiscing elit, sed do eiusmod tempor incididunt 
        ut labore et dolore magna aliqua. </p>
      </a>
    </div>
  

    <div class="box col3">
        <a href="#">
        <%= image_tag("image_S_3.jpg", alt: "HOT TOPICS")%>
        <div class="category">HOT TOPICS</div>
        <p class="description">Lorem ipsum dolor sit amet, 
        consectetur adipiscing elit, sed do eiusmod tempor incididunt 
        ut labore et dolore magna aliqua. </p>
      </a>
    </div>

  <div class="box col1">
        <a href="#">
        <%= image_tag("image_S_1.jpg", alt: "HOT TOPICS")%>
        <div class="category">HOT TOPICS</div>
        <p class="description">Lorem ipsum dolor sit amet... </p>
      </a>
    </div>

    <div class="box col4">
      <a href="#">
      <%= image_tag("image_M_3.jpg", alt: "HOT TOPICS")%>
      <div class="category">HOT TOPICS</div>
      <p class="description">Lorem ipsum dolor sit amet, 
      consectetur adipiscing elit, sed do eiusmod tempor incididunt 
      ut labore et dolore magna aliqua. </p>
      </a>
   </div>

    <div class="box col5">
        <a href="#">
        <%= image_tag("image_M_4.jpg", alt: "HOT TOPICS")%>
        <div class="category">HOT TOPICS</div>
        <p class="description">Lorem ipsum dolor sit amet, 
        consectetur adipiscing elit, sed do eiusmod tempor incididunt 
        ut labore et dolore magna aliqua. </p>
      </a>
    </div>

</div>

<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
<footer class="footer">
  <ul class="horizontal-list">
      <li class="horizontal-item"><a href="#">ABOUT US</a></li>
      <li class="horizontal-item"><a href="#">SITE MAP</a></li>
      <li class="horizontal-item"><a href="#">SNS</a></li>
      <li class="horizontal-item"><a href="#">CONTACT</a></li>
  </ul>
</footer>
</div>

app/views/events/new.html.erb
<h1> やさい箱 投稿フォーム </h1><br>

<%= render 'layouts/error_messages', model: @event %>

 <%= form_with(model: @event, local: true) do |f| %>

       <div class="weight-bold-text">
       (1) 箱の呼び名
        <span class="indispensable">必須</span>
      </div><br>
     <p>
      <%= f.text_area :event_name, class:"items-text", id:"item-name", placeholder:"箱のn名前（必須 40文字まで)", maxlength:"40" %>
     </p> 
   </div><br>

       (２) 箱の中身ついて（野菜の種類、数量など）
        <span class="indispensable">必須</span>
      </div><br>
     <p>
      <%= f.text_area :event_name, class:"items-text", id:"item-name", placeholder:"箱の内容について記述（必須 40文字まで)", maxlength:"40" %>
     </p> 
   </div><br>

    <div class="weight-bold-text">
     (３) 設置場所データ（すでに登録済みの箱の設置場所を選択してください） <span class="indispensable">必須</span><br><br>
          <p>  
            <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"area-select"}) %>
          </p>
     <br>
    <%# 設置場所の画像 %>
  <div class="new-items">
    <div class="img-upload">
      <div class="weight-bold-text">
        (3) 箱の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
         ** クリックしてファイルをアップロード（拡張子が「.png」または「.jpeg」の画像を投稿してください。**
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
  </div>
   
  <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "箱設置場所を投稿",class:"sell-btn" %>
     </div><br>
      
    <div class="sell-btn-contents">
     <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>

app/views/events/show.html.erb
<h1>Haco 詳細</h1>
<p>設置時期、住所、地図</p>


  <h2 class="name">
      <%= @spot.spot_name %>
  </h2>
    <div>
      <%= image_tag @spot.image %>
    </div>
   
    <div>
      <span>
        <%= @spot_area_id %>
      </span>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @spot.user_id %>
        <%= link_to "編集", edit_spot_path(@spot.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", spot_path(@spot.id), method: :delete, class:"item-destroy" %>
      <% else %>
        <%= link_to "購入画面に進む", spot_orders_path(@spot.id) ,class:"item-red-btn" %>
      <% end %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="item_name">設置場所名</th>
          <td class="item-value"><%= @spot.spot_name %></td>
        </tr>
        <tr>
          <th class="detail-spot">エリア(番号直接入力？）</th>
          <td class="detail-value"><%= @spot.spot_area_id %></td>
        </tr>
        <tr>
          <th class="detail-spot">郵便番号</th>
          <td class="detail-value"><%= @spot.postal_code %></td>
        </tr>
        <tr>
          <th class="detail-spot">住所</th>
          <td class="detail-value"><%= @spot.address %></td>
        </tr>
        <tr>
          <th class="detail-spot">建物名</th>
          <td class="detail-value"><%= @spot.building %></td>
        </tr>
        <tr>
          <th class="detail-spot">電話番号</th>
          <td class="detail-value"><%= @spot.phone_number %></td>
        </tr>
      </tbody>
   

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Haco ni やさい</title>
   <%= csrf_meta_tag %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# 上記の記述でwebpackで管理されているJavaScriptを参照 %>
     <!-- CDN -->
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
    
   <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />
   <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>


  </head>

 <body> 
  <div>
  <h1><%= link_to image_tag("logo_title.png", alt: "LOGO TITLE"), "/" %></h1> <br><br><br>
</div>
  
    <%= yield %>
 </body>

</html>

app/views/spots/_main_page.html.erb
<h1>Haco どこ？</h1><br><br><br>
<h2>出品場所一覧 （エリア: １高松市、２東讃、３中讃、４西讃、５島エリア）</h2><br>


  <table class="list">
  <thead>
    <tr>
      <th>画像</th>
      <th>Spot No.</th>
      <th>エリアno.</th>
      <th>スポット名</th>
      <th>住所</th>
      <th>詳細</th>
      

    </tr>
  </thead>
  <tbody>

<% if @spots.present? %>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= image_tag spot.image.variant(resize: '90x90'), class: 'item-image' if spot.image.attached? %></td>
        <td><%= spot.id%></td>
        <td><%= spot.area_id %></td>
        <td><%= spot.spot_name %></td>
        <td><%= spot.address %></td>
        <td><%= link_to '詳細', spot_path(spot.id), method: :get %></td>
      </tr>
    <% end %> 
  <% end %>
  </tbody>
  </table>
  <br>

  <div>
  
  </div>

app/views/spots/_map.html.erb
<div><h2>
------ MAP ------
</h2></div>

<div id="map"></div>
  <style type="text/css">
    #map {
      height:400px;
    }
  </style>
  <script type="text/javascript">
        L.Icon.Default.imagePath = "/assets";
        var map = L.map('map').setView([緯度, 経度],17);
        var osmUrl = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
        var osmAttrib = "Map data OpenstreetMap contributors";
        L.tileLayer(osmUrl,{
          attribution: osmAttrib,
          maxZoom: 20,
        }).addTo(map);

var marker = L.marker([緯度, 経度]).addTo(map);

        map.on("click",function(e){
          marker.setLatLng(e.latlng);
          $('#map_latitude').val(e.latlng.lat);
          $('#map_longitude').val(e.latlng.lng);
        });

</script>

app/views/spots/_side_menu.html.erb
<header>
  <%# // rout page へ遷移%>
  <%= link_to image_tag("logo.png", size: "80x80", alt: "Logo"), "/" %>


<nav>
     <ul class="global-nav"><br><br>

   <% if user_signed_in? %>  
     <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: :"nav-item" %></li><br> 
  <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: :"nav-item" %></li><br>

      <li><%= link_to '新規登録', new_user_registration_path, class: :"nav-item" %><br>
    <%# // ユーザーがログアウトしている場合に実行する処理 %>
  <% end %>

        <% if user_signed_in? %>
        <li><a class="nav-item" href="#">MY PAGE</a></li><br>

        <li><a class="nav-item" href="#">出品場所ごと</a></li><br>
        <li><a class="nav-item" href="#">カレンダー</a></li><br>
        <li><a class="nav-item" href="#">エリア別情報</a></li><br>
          <% else %>
          <li><a class="nav-item" href="#">出品場所ごと</a></li><br>
          <li><a class="nav-item" href="#">カレンダー</a></li><br>
          <li><a class="nav-item" href="#">エリア別情報</a></li><br>
          <% end %>
        </ul>
      </div>
      </nav>
    </header>

app/views/spots/edit.html.erb
<h1> 箱設置場所 新規投稿フォーム </h1><br>

<%= render 'layouts/error_messages', model: @spot %>

 <%= form_with(model: @spot, local: true) do |f| %>

    <%# <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
 
       <div class="weight-bold-text">
       (1) 設置場所名（店名、農場名、場所名）
        <span class="indispensable">必須</span>
      </div><br>
     <p>
      <%= f.text_area :spot_name, class:"items-text", id:"item-name", placeholder:"設置場所名（店舗、農場名など）（必須 40文字まで)", maxlength:"40" %>
     </p> 
   </div><br>
    <div class="weight-bold-text">
     (2) 設置場所のエリア（選択してください） <span class="indispensable">必須</span><br><br>
          <p>  
            <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"area-select"}) %>
          </p>
     <br>
    <%# 設置場所の画像 %>
  <div class="new-items">
    <div class="img-upload">
      <div class="weight-bold-text">
        (3) 設置場所の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
         ** クリックしてファイルをアップロード（拡張子が「.png」または「.jpeg」の画像を投稿してください。**
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
  </div>
   
    <div>
         <div class="weight-bold-text">
          <label class="form-text">(4) 郵便番号</label>
          <span class="indispensable">必須</span>
        </div><br>
        <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div><br>
  
     <div>
       <div class="weight-bold-text">
        (5) 設置場所の住所
        <span class="indispensable">必須</span>
      </div><br>
        <p>
          <%= f.text_area :address, class:"items-text", id:"item-name", placeholder:"設置場所の住所（必須 40文字まで)", maxlength:"40" %>
        </p> 
     </div>
       <div class="weight-bold-text">
        (6) 設置場所の建物名（ビル名などあれば記入）：任意
      </div><br>
        <p>
          <%= f.text_area :building, class:"items-text", id:"item-name", placeholder:"ビルなどの建物名（ある場合記入：40文字まで)", maxlength:"20" %>
        </p> 
     </div><br>

     <div>
       <div class="weight-bold-text">
         (7) 連絡先（電話番号）
        <span class="indispensable">必須</span>
      </div>
    <p>
      <%= f.text_area :phone_number, class:"items-text", id:"item-name", placeholder:"電話番号（必須 ハイフンなし、半角１０−１１文字)", maxlength:"11" %>
     </p> 
    </div><br>

   
  <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "編集内容を反映する",class:"sell-btn" %>
     </div><br>
      
    <div class="sell-btn-contents">
     <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  <% end %>
  <br>
  <% end %>

app/views/spots/index.html.erb
<div class="wrapper">
   <div class="side_menu">   
      <%= render "side_menu" %>
   </div> 

     <div class="main_page">
      <%= render "main_page" %>
      
    </div> 

app/views/spots/show.html.erb
<div class="contents row">
    <h1 class="name">
      詳細情報：<%= @spot.spot_name %>
    </h1>
    <div>
      <% if @spot.image.attached? %>
      <%= image_tag @spot.image %>
      <% else %>
      ( Spot 画像がありません )
      <%# <%= image_tag "#"%> 
      <% end %>
     
    </div><br>

 <table class="list">
  
  <tr>
    <th>Spot No.</th>
        <td><%= @spot.id%></td>
    </tr>
  <tr>
      <th>エリアno.</th>
        <td><%= @spot.area_id %></td>
  </tr>
  <tr>
      <th>スポット名</th>
         <td><%= @spot.spot_name %></td>
    </tr>
  <tr>
       <th>郵便番号</th>
        <td><%= @spot.postal_code %></td>
    </tr>
  <tr>
      <th>住所</th>
        <td><%= @spot.address %></td>
  </tr>
  <tr>
      <th>電話</th>
        <td><%= @spot.phone_number %></td>
  </tr> 
  <tr>
      <th>編集</th>
        <td><%= link_to '編集', edit_spot_path(@spot.id), method: :get %></td>
    </tr>
  <tr>
      <th>削除</th>
        <td><%= link_to '削除', spot_path(@spot.id), method: :delete %></td>
    </tr>

  </table><br>

<%# https://www.openstreetmap.org/#map=10/34.2778/133.9865 %>

    </span>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップページに戻る", root_path, method: :get, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>